force-app/main/default/objects/GMOPaymentBean__c/GMOPaymentBean__c.object-meta.xml
<CustomObject>
    <label>GMOPaymentBean</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>GMOPaymentBean Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GMOPaymentBean__c/fields/item_name__c.field-meta.xml
<CustomField>
    <fullName>item_name__c</fullName>
    <label>item_name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/item_price__c.field-meta.xml
<CustomField>
    <fullName>item_price__c</fullName>
    <label>item_price</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/order_number__c.field-meta.xml
<CustomField>
    <fullName>order_number__c</fullName>
    <label>order_number</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/st_code__c.field-meta.xml
<CustomField>
    <fullName>st_code__c</fullName>
    <label>st_code</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/trans_code__c.field-meta.xml
<CustomField>
    <fullName>trans_code__c</fullName>
    <label>trans_code</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/user_id__c.field-meta.xml
<CustomField>
    <fullName>user_id__c</fullName>
    <label>user_id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionGMOPaymentBean__c/SubscriptionGMOPaymentBean__c.object-meta.xml
<CustomObject>
    <label>SubscriptionGMOPaymentBean</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>SubscriptionGMOPaymentBean Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionGMOPaymentBean__c/fields/GMOPaymentBeanId__c.field-meta.xml
<CustomField>
    <fullName>GMOPaymentBeanId__c</fullName>
    <label>GMOPaymentBeanId</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionGMOPaymentBean__c/fields/SubscriptionId__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionId__c</fullName>
    <label>SubscriptionId</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/viewModel/PaymentResultViewModel.cls
public with sharing class PaymentResultViewModel {
    public GMOPaymentBean__c gmoPaymentBean {get; set;}

    public PaymentResultViewModel(String orderId) {
        gmoPaymentBean = [SELECT trans_code__c, order_number__c, item_price__c, item_name__c, st_code__c, user_id__c 
                        FROM GMOPaymentBean__c WHERE order_number__c = :orderId];
    }

    public SubscriptionGMOPaymentBean__c getSubGMOPaymentBean(String orderId) {
        List<SubscriptionGMOPaymentBean__c> subGMOPaymentBeans = [SELECT GMOPaymentBeanId__c, SubscriptionId__c FROM SubscriptionGMOPaymentBean__c
                            WHERE GMOPaymentBeanId__c = :orderId];
        if (subGMOPaymentBeans.size() != 1) 
            return null;

        return subGMOPaymentBeans.get(0);
    }

    public Account getAccount(String accountId) {
        Account account = AccountModel.getAccountById(accountId);
        return account;
    }
}