force-app/main/default/objects/GMOPaymentBean__c/GMOPaymentBean__c.object-meta.xml
<CustomObject>
    <label>GMOPaymentBean</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>GMOPaymentBean Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GMOPaymentBean__c/fields/add_info1__c.field-meta.xml
<CustomField>
    <fullName>add_info1__c</fullName>
    <label>add_info1</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/card_holder_name__c.field-meta.xml
<CustomField>
    <fullName>card_holder_name__c</fullName>
    <label>card_holder_name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/card_number__c.field-meta.xml
<CustomField>
    <fullName>card_number__c</fullName>
    <label>card_number</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/character_code__c.field-meta.xml
<CustomField>
    <fullName>character_code__c</fullName>
    <label>character_code</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/contract_code__c.field-meta.xml
<CustomField>
    <fullName>contract_code__c</fullName>
    <label>contract_code</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/currency_id__c.field-meta.xml
<CustomField>
    <fullName>currency_id__c</fullName>
    <label>currency_id</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/expire_month__c.field-meta.xml
<CustomField>
    <fullName>expire_month__c</fullName>
    <label>expire_month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/expire_year__c.field-meta.xml
<CustomField>
    <fullName>expire_year__c</fullName>
    <label>expire_year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/ip_address__c.field-meta.xml
<CustomField>
    <fullName>ip_address__c</fullName>
    <label>ip_address</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/item_code__c.field-meta.xml
<CustomField>
    <fullName>item_code__c</fullName>
    <label>item_code</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/item_name__c.field-meta.xml
<CustomField>
    <fullName>item_name__c</fullName>
    <label>item_name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/item_price__c.field-meta.xml
<CustomField>
    <fullName>item_price__c</fullName>
    <label>item_price</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/lang_id__c.field-meta.xml
<CustomField>
    <fullName>lang_id__c</fullName>
    <label>lang_id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/mission_code__c.field-meta.xml
<CustomField>
    <fullName>mission_code__c</fullName>
    <label>mission_code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/order_number__c.field-meta.xml
<CustomField>
    <fullName>order_number__c</fullName>
    <label>order_number</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/pan_bank__c.field-meta.xml
<CustomField>
    <fullName>pan_bank__c</fullName>
    <label>pan_bank</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/pan_country__c.field-meta.xml
<CustomField>
    <fullName>pan_country__c</fullName>
    <label>pan_country</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/process_code__c.field-meta.xml
<CustomField>
    <fullName>process_code__c</fullName>
    <label>process_code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/result__c.field-meta.xml
<CustomField>
    <fullName>result__c</fullName>
    <label>result</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/security_code__c.field-meta.xml
<CustomField>
    <fullName>security_code__c</fullName>
    <label>security_code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/st_code__c.field-meta.xml
<CustomField>
    <fullName>st_code__c</fullName>
    <label>st_code</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/user_agent__c.field-meta.xml
<CustomField>
    <fullName>user_agent__c</fullName>
    <label>user_agent</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/user_id__c.field-meta.xml
<CustomField>
    <fullName>user_id__c</fullName>
    <label>user_id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/user_mail_add__c.field-meta.xml
<CustomField>
    <fullName>user_mail_add__c</fullName>
    <label>user_mail_add</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/user_name__c.field-meta.xml
<CustomField>
    <fullName>user_name__c</fullName>
    <label>user_name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/version__c.field-meta.xml
<CustomField>
    <fullName>version__c</fullName>
    <label>version</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/test/GMOPaymentAPITest.cls
@isTest
public class GMOPaymentAPITest {
    public static GMOPaymentBean__c buildGMOPaymentBean() {
        GMOPaymentBean__c gmoPaymentBean = new GMOPaymentBean__c();

        gmoPaymentBean.contract_code__c = '10081070';
        gmoPaymentBean.version__c = '1';
        gmoPaymentBean.process_code__c = '1';
        gmoPaymentBean.user_id__c = 'test0001';
        gmoPaymentBean.user_name__c = 'Yamada Tarou';
        gmoPaymentBean.user_mail_add__c = 'test@test.com';
        gmoPaymentBean.lang_id__c = 'en';
        gmoPaymentBean.ip_address__c = '111.250.156.96';
        gmoPaymentBean.user_agent__c = 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36';
        gmoPaymentBean.item_code__c = 'GP-0001';
        gmoPaymentBean.item_name__c = 'Apple';
        gmoPaymentBean.order_number__c = Datetime.now().format('yyyyMMddHHmmss');
        gmoPaymentBean.st_code__c = '10000-00000-00000-00000-00000-00000-00000';
        gmoPaymentBean.mission_code__c = '1';
        gmoPaymentBean.currency_id__c = 'TWD';
        gmoPaymentBean.item_price__c = '840';
        gmoPaymentBean.card_number__c = '4234567890123456';
        gmoPaymentBean.expire_year__c = '2020';
        gmoPaymentBean.expire_month__c = '12';
        gmoPaymentBean.security_code__c = '123';
        gmoPaymentBean.pan_bank__c = 'CitiBank';
        gmoPaymentBean.pan_country__c = 'TW';
        gmoPaymentBean.card_holder_name__c = 'TOM YAMADA';
        gmoPaymentBean.add_info1__c = '1';

        return gmoPaymentBean;
    }

    public static String buildDirectPaymentResponse() {
        return '<?xml version="1.0" encoding="UTF-8" ?>' +
        '<GlobalPayment_result>' +
        '    <result result="9" />' +
        '    <result trans_code="" />' +
        '    <result err_code="LO01000013" />' +
        '    <result err_detail="Card%20information%20is%20incorrect%20%28NEWEB%20order%20information%20acquisition%20error%29" />' +
        '    <result access_url="" />' +
        '    <result trans_code_hash="" />' +
        '    <result payment_code="" />' +
        '    <result mode="" />' +
        '    <result status="" />' +
        '</GlobalPayment_result>';
    }

    public static testMethod void testAddCommonGMOPaymentBeanValues() {
        GMOPaymentBean__c gmoPaymentBean = buildGMOPaymentBean();
        GMOPaymentAPI api = new GMOPaymentAPI(gmoPaymentBean);
        gmoPaymentBean = api.addCommonGMOPaymentBeanValues(gmoPaymentBean);

        System.assertEquals('UTF-8', gmoPaymentBean.character_code__c);
    }

    public static testMethod void testBuildGMOPaymentBodyForDirectPayment() {
        GMOPaymentBean__c gmoPaymentBean = buildGMOPaymentBean();
        GMOPaymentAPI api = new GMOPaymentAPI(gmoPaymentBean);
        String actual = api.buildGMOPaymentBodyForDirectPayment(gmoPaymentBean);
        System.assert(actual.length() > 0);
    }

    public static testMethod void test_getPaymentMethodFromStCode() {
        GMOPaymentBean__c gmoPaymentBean = buildGMOPaymentBean();
        GMOPaymentAPI api = new GMOPaymentAPI(gmoPaymentBean);
        String actual = api.getPaymentMethodFromStCode(Constants.ST_CODE_CREDIT_CARD_PAYMENT);
        System.assertEquals(Constants.PAYMENT_METHOD_CREDIT_CARD, actual);
        
        actual = api.getPaymentMethodFromStCode(Constants.ST_CODE_ATM);
        System.assertEquals(Constants.PAYMENT_METHOD_ATM, actual);

        actual = api.getPaymentMethodFromStCode(Constants.ST_CODE_SUPER_PAYMENT);
        System.assertEquals(Constants.PAYMENT_METHOD_SUPER_PAYMENT, actual);

        actual = api.getPaymentMethodFromStCode(Constants.ST_CODE_NOTHING);
        System.assertEquals('', actual);
    }

    public static testMethod void test_generateProcessCode() {
        String actual = GMOPaymentAPI.generateProcessCode(Constants.PAYMENT_METHOD_CREDIT_CARD);
        System.assertEquals(Constants.PROCESS_CODE_REGISTER_CREDIT_CARD, actual);
        
        actual = GMOPaymentAPI.generateProcessCode(Constants.PAYMENT_METHOD_SUPER_PAYMENT);
        System.assertEquals(Constants.PROCESS_CODE_ONE_TIME, actual);
    }

    public static testMethod void test_generateStCode() {
        String actual = GMOPaymentAPI.generateStCode(Constants.PAYMENT_METHOD_CREDIT_CARD);
        System.assertEquals(Constants.ST_CODE_CREDIT_CARD_PAYMENT, actual);
        
        actual = GMOPaymentAPI.generateStCode(Constants.PAYMENT_METHOD_ATM);
        System.assertEquals(Constants.ST_CODE_ATM, actual);

        actual = GMOPaymentAPI.generateStCode(Constants.PAYMENT_METHOD_SUPER_PAYMENT);
        System.assertEquals(Constants.ST_CODE_SUPER_PAYMENT, actual);

        actual = GMOPaymentAPI.generateStCode('');
        System.assertEquals(Constants.ST_CODE_NOTHING, actual);
    }

    public static testMethod void test_deserializationGMOResponse() {
        GMOPaymentBean__c gmoPaymentBean = buildGMOPaymentBean();
        GMOPaymentAPI api = new GMOPaymentAPI(gmoPaymentBean);
        GMOPaymentBean__c beanAPIResponse = (GMOPaymentBean__c) api.deserializationGMOResponse(buildDirectPaymentResponse(), GMOPaymentBean__c.class);
        String actual = beanAPIResponse.result__c;
        System.assertEquals('9', actual);
    }
    
}