force-app/main/default/objects/GMOPaymentBean__c/GMOPaymentBean__c.object-meta.xml
<CustomObject>
    <label>GMOPaymentBean</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>GMOPaymentBean Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GMOPaymentBean__c/fields/trans_code__c.field-meta.xml
<CustomField>
    <fullName>trans_code__c</fullName>
    <label>trans_code</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>訂閱</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}{000}</displayFormat>
        <label>訂單編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Payment_method__c.field-meta.xml
<CustomField>
    <fullName>Payment_method__c</fullName>
    <label>付款方式</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>信用卡</fullName>
            </value>
            <value>
                <fullName>超商付款</fullName>
            </value>
            <value>
                <fullName>ATM轉帳</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Payment_status__c.field-meta.xml
<CustomField>
    <fullName>Payment_status__c</fullName>
    <label>付款狀態</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>paymentpending</fullName>
                <default>true</default>
                <label>待付款</label>
            </value>
            <value>
                <fullName>paymentdone</fullName>
                <label>已付款</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SubscriptionGMOPaymentBean__c/SubscriptionGMOPaymentBean__c.object-meta.xml
<CustomObject>
    <label>SubscriptionGMOPaymentBean</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>SubscriptionGMOPaymentBean Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionGMOPaymentBean__c/fields/GMOPaymentBeanId__c.field-meta.xml
<CustomField>
    <fullName>GMOPaymentBeanId__c</fullName>
    <label>GMOPaymentBeanId</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionGMOPaymentBean__c/fields/SubscriptionId__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionId__c</fullName>
    <label>SubscriptionId</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/cronjob/CheckPaymentJob.cls
global class CheckPaymentJob implements Schedulable {

    global static String scheduleIt(String name, String cronExpr) {
        CheckPaymentJob job = new CheckPaymentJob();
        return System.schedule(name, cronExpr, job);
    }
  
    global void execute(SchedulableContext sc) {
        System.debug('Cron executed at ' + Datetime.now().format('yyyyMMddHHmmss'));
        checkPayment();
    }

    public void checkPayment() {
        List<Subscription__c> subscriptions = 
            [SELECT Id
            FROM Subscription__c 
            WHERE Payment_method__c != :Constants.PAYMENT_METHOD_CREDIT_CARD
            AND Payment_Status__c = :Constants.PAYMENT_STATUS_PENDING
            LIMIT 10];
        
        if (subscriptions.size() <= 0)
            return;

        List<Id> subIds = new List<Id>();
        for (Subscription__c sub : subscriptions)
            subIds.add(sub.Id);

        List<SubscriptionGMOPaymentBean__c> subGmoPaymentBeans = [SELECT SubscriptionId__c, GMOPaymentBeanId__c 
                                                                FROM SubscriptionGMOPaymentBean__c 
                                                                WHERE SubscriptionId__c in :subIds];

        List<Id> gmoPaymentBeanIds = new List<Id>();
        for (SubscriptionGMOPaymentBean__c subGmoPaymentBean : subGmoPaymentBeans)
            gmoPaymentBeanIds.add(subGmoPaymentBean.GMOPaymentBeanId__c);

        List<GMOPaymentBean__c> gmoPaymentBeans = [SELECT trans_code__c
                                                FROM GMOPaymentBean__c
                                                WHERE Id in :gmoPaymentBeanIds];
        
        for (Subscription__c subscription : subscriptions) {
            Id gmoPaymentBeanId = findGMOPaymentBeanIdGivenSubscription(subGmoPaymentBeans, subscription.Id);
            GMOPaymentBean__c gmoPaymentBean = findGMOPaymentBeanObject(gmoPaymentBeans, gmoPaymentBeanId);

            CheckPaymentBatchJob job = new CheckPaymentBatchJob(subscription, gmoPaymentBean.trans_code__c);
            Database.executeBatch(job);
        }    
    }

    public Id findGMOPaymentBeanIdGivenSubscription(List<SubscriptionGMOPaymentBean__c> subGmoPaymentBeans, Id subscriptionId) {
        for (SubscriptionGMOPaymentBean__c subGmoPaymentBean : subGmoPaymentBeans)
            if (subGmoPaymentBean.SubscriptionId__c == subscriptionId)
                return subGmoPaymentBean.GMOPaymentBeanId__c;
        return null;
    }

    public GMOPaymentBean__c findGMOPaymentBeanObject(List<GMOPaymentBean__c> gmoPaymentBeans, Id gmoPaymentBeanId) {
        for (GMOPaymentBean__c gmoPaymentBean : gmoPaymentBeans)
            if (gmoPaymentBean.Id == gmoPaymentBeanId)
                return gmoPaymentBean;
        return null;
    }
}