force-app/main/default/objects/GMOPaymentBean__c/GMOPaymentBean__c.object-meta.xml
<CustomObject>
    <label>GMOPaymentBean</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>GMOPaymentBean Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GMOPaymentBean__c/fields/contract_code__c.field-meta.xml
<CustomField>
    <fullName>contract_code__c</fullName>
    <label>contract_code</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/order_number__c.field-meta.xml
<CustomField>
    <fullName>order_number__c</fullName>
    <label>order_number</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/st_code__c.field-meta.xml
<CustomField>
    <fullName>st_code__c</fullName>
    <label>st_code</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/fields/trans_code__c.field-meta.xml
<CustomField>
    <fullName>trans_code__c</fullName>
    <label>trans_code</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionGMOPaymentBean__c/SubscriptionGMOPaymentBean__c.object-meta.xml
<CustomObject>
    <label>SubscriptionGMOPaymentBean</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>SubscriptionGMOPaymentBean Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionGMOPaymentBean__c/fields/GMOPaymentBeanId__c.field-meta.xml
<CustomField>
    <fullName>GMOPaymentBeanId__c</fullName>
    <label>GMOPaymentBeanId</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/test/PaymentResultViewModelTestCases.cls
@isTest
public with sharing class PaymentResultViewModelTestCases {
    public static testMethod void testConstructor() {
        GMOPaymentBean__c paymentBean = new GMOPaymentBean__c(contract_code__c = '10081070', order_number__c = '784420180802115557', st_code__c = '00010-00000-00000-00000-00000-00000-00000', trans_code__c = '131551');
        insert paymentBean;
        PaymentResultViewModel viewModel = new PaymentResultViewModel(paymentBean.order_number__c);
        System.assertNotEquals(null, viewModel.gmoPaymentBean);
    }

    public static testMethod void testGetSubGMOPaymentBean_Null_Return_Null() {
        GMOPaymentBean__c paymentBean = new GMOPaymentBean__c(contract_code__c = '10081070', order_number__c = '784420180802115557', st_code__c = '00010-00000-00000-00000-00000-00000-00000', trans_code__c = '131551');
        insert paymentBean;
        PaymentResultViewModel viewModel = new PaymentResultViewModel(paymentBean.order_number__c);
        SubscriptionGMOPaymentBean__c subGMOPaymentBean = viewModel.getSubGMOPaymentBean(paymentBean.order_number__c);
        System.assertEquals(null, subGMOPaymentBean);
    }

    public static testMethod void testGetSubGMOPaymentBean_Not_Null() {
        GMOPaymentBean__c paymentBean = new GMOPaymentBean__c(contract_code__c = '10081070', order_number__c = '784420180802115557', st_code__c = '00010-00000-00000-00000-00000-00000-00000', trans_code__c = '131551');
        insert paymentBean;
        SubscriptionGMOPaymentBean__c tempSubGMOPaymentBean = new SubscriptionGMOPaymentBean__c(GMOPaymentBeanId__c = '784420180802115557');
        insert tempSubGMOPaymentBean;
        PaymentResultViewModel viewModel = new PaymentResultViewModel(paymentBean.order_number__c);
        SubscriptionGMOPaymentBean__c subGMOPaymentBean = viewModel.getSubGMOPaymentBean(paymentBean.order_number__c);
        System.assertNotEquals(null, subGMOPaymentBean);
    }

    public static testMethod void testGetAccount() {
        Account tempAccount = new Account(LastName = 'jin');
        insert tempAccount;
        GMOPaymentBean__c paymentBean = new GMOPaymentBean__c(contract_code__c = '10081070', order_number__c = '784420180802115557', st_code__c = '00010-00000-00000-00000-00000-00000-00000', trans_code__c = '131551');
        insert paymentBean;
        PaymentResultViewModel viewModel = new PaymentResultViewModel(paymentBean.order_number__c);
        Account account = viewModel.getAccount(tempAccount.id);
        System.assertNotEquals(null, account);
    }
}