force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>驗證通過</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>12</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>帳戶</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>帳戶</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>啟用</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>密码</label>
    <length>12</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/viewModel/ChangePasswordViewModel.cls
public with sharing class ChangePasswordViewModel {
    
    public Account__c account {get; set;}
    public Account__c accountVerify {get; set;}    
    private String errorMessage {get; set;}


    public ChangePasswordViewModel(String accountId) {
        account = AccountModel.getAccountById(accountId);
        account.Password__c = '';
        accountVerify = new Account__c();
        accountVerify.Password__c = account.Password__c;
        
    }

    public Boolean submit() {
        if (checkPassword() == true) {
            account.Active__c = true;
            Database.SaveResult result = Database.update(account);
            return result.isSuccess();
        }  
        return false; 
    }

    public Boolean checkPassword() {
        Boolean result = true;
        String password = account.Password__c;
        if (PasswordUtility.checkPasswordHasEnglish(password) == false) {
            clearPassword();
            errorMessage = '密碼長度需8~12碼，且至少需要一個數字和英文';
            result = false;
        } else if (password.equals(accountVerify.Password__c) == false) {
            clearPassword();
            errorMessage = '密碼與驗證密碼不相符';
            result = false;            
        }
        return result;
    }
    
    private void clearPassword() {
        account.Password__c = '';
        accountVerify.Password__c = '';
    }
    
    public String getErrorMessage() {
        return errorMessage;
    }
    
}