force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>驗證通過</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/JoinDate__c.field-meta.xml
<CustomField>
    <fullName>JoinDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>加入日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Locked__c.field-meta.xml
<CustomField>
    <fullName>Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>鎖定</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>12</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/PasswordRetry__c.field-meta.xml
<CustomField>
    <fullName>PasswordRetry__c</fullName>
    <defaultValue>0</defaultValue>
    <label>密碼輸入錯誤次數</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>帳戶</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>帳戶</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>啟用</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>電子郵件</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account__c/fields/JoinDate__c.field-meta.xml
<CustomField>
    <fullName>JoinDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>加入日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>名字</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>密码</label>
    <length>12</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <label>Token</label>
    <length>32</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/model/AccountModel.cls
public with sharing class AccountModel {
    public static Account__c getAccountById(String userId) {
        return [Select Active__c, Locked__c, Email__c, PasswordRetry__c, LastName__c, Password__c, JoinDate__c from Account__c where Id = :userId];
    }

    public static Account__c getAccountByEmail(String email) {
        List<Account__c> accounts = [Select Id, PasswordRetry__c, Locked__c, Active__c, Email__c, LastName__c, Password__c from Account__c where Email__c = :email];
        if (accounts.size() > 0) {
            return accounts.get(0);
        } else { 
            return null;
        }
    }

    public static void lockAccountForThreeTimes(Account__c account) {
        account.Locked__c = true;
        update account;
    }

    public static String saveToken(Account__c account) {
        String token = AuthUtility.generateToken();
        account.Token__c = token;
        update account;
        return token;
    }

    public static Boolean updateAccount(Account__c account) {
        Database.SaveResult result = Database.update(account); 
        return result.isSuccess();
    }

    public static Account__c createAccountByEmail(String email) {
        List<Account__c> accounts = [Select Id from Account__c where Email__c = :email];
        if (accounts.size() > 0)
            return null;

        Account__c account = new Account__c(Email__c = email, LastName__c = email);
        insert account;
        
        return account;
    }

    public static Account__c createAccountByEmail(String email, String lastName) {
        List<Account__c> accounts = [Select Id from Account__c where Email__c = :email];
        if (accounts.size() > 0)
            return null;
        
        Account__c account = new Account__c(Email__c = email, LastName__c = lastName);
        insert account;

        return account;
    }
}