force-app/main/default/objects/Account/fields/credit_card_number__c.field-meta.xml
<CustomField>
    <fullName>credit_card_number__c</fullName>
    <label>信用卡號</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CVC__c.field-meta.xml
<CustomField>
    <fullName>CVC__c</fullName>
    <label>CVC</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Expiration_month__c.field-meta.xml
<CustomField>
    <fullName>Expiration_month__c</fullName>
    <label>到期月份</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Expiration_Year_text__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Year_text__c</fullName>
    <label>到期年份</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>帳戶</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>帳戶</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/credit_card_number__c.field-meta.xml
<CustomField>
    <fullName>credit_card_number__c</fullName>
    <label>信用卡號</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/CVC__c.field-meta.xml
<CustomField>
    <fullName>CVC__c</fullName>
    <label>CVC</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Expiration_month__c.field-meta.xml
<CustomField>
    <fullName>Expiration_month__c</fullName>
    <label>到期月份</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <default>true</default>
                <label>01</label>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account__c/fields/Expiration_Year_text__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Year_text__c</fullName>
    <label>到期年份</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>訂閱</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}{000}</displayFormat>
        <label>訂單編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/isReplenish__c.field-meta.xml
<CustomField>
    <fullName>isReplenish__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動續訂</label>
    <type>Checkbox</type>
</CustomField>

force-app/controller/UpdateCreditCardController.cls
public with sharing class UpdateCreditCardController extends ApexBaseController {
    public UpdateCreditCardViewModel viewModel {get; set;}
    private Account__c tempAccount {get; set;}
    public List<SelectOption> year {get; set;}
    public String subscriptionId {get; set;} 

    public UpdateCreditCardController() {
		Cookie accountIdCookie = ApexPages.currentPage().getCookies().get(Label.COOKIE_ACCOUNT_ID);
        
        if (accountIdCookie != null) {
            String accountId = accountIdCookie.getValue();
        	subscriptionId = ApexPages.currentpage().getparameters().get('subscriptionId');
            viewModel = new UpdateCreditCardViewModel(accountId);  
            tempAccount = viewModel.account.clone();
            viewModel.account.CVC__c = '';
        }    
    }

    public Pagereference updateCreditcard() {
        if (checkField()) {
            if (viewModel.account.credit_card_number__c != null && !String.isBlank(viewModel.account.credit_card_number__c))
                viewModel.account.credit_card_number__c = EncryptionUtility.encrypt(viewModel.account.credit_card_number__c);

            if(viewModel.updateAccount()) 
                if(updateReplenish()) {
                    addMessage(ApexPages.Severity.INFO, System.Label.Msg_UpdateCompleted);
                    PageReference page = ApexUtility.toPage('SubscriptionManagementPage');
                    page.getParameters().put('updateCreditcard','true');
                    return page;    
                }     
        }      
        return null;
    }

    public Pagereference cancel() {
        rollbackAccount();  
        return ApexUtility.toPage('SubscriptionManagementPage');
    }

    public List<SelectOption> getCreditcard_Year (){
        year = new List<SelectOption>();
        Integer yearFornow = Integer.valueOf(System.now().format('Y'));
        year.add(new SelectOption('','--None--'));
        for(Integer i=0; i<13; i++){
            year.add(new SelectOption(String.valueOf(yearFornow + i),String.valueOf(yearFornow + i)));
        }
        return year;
    }

    private Boolean checkField() {
        if (viewModel.account.credit_card_number__c == null || viewModel.account.Expiration_month__c == null ||
                viewModel.account.Expiration_Year_text__c == null || viewModel.account.Expiration_Year_text__c == '' ||
                viewModel.account.CVC__c == null){
            addMessage(ApexPages.Severity.ERROR, System.Label.Msg_Creditcard_CheckAll);
            return false;
        } 

        if (!CreditcardUtility.isCreditCardPattenMatching(viewModel.account.credit_card_number__c)) {
            addMessage(ApexPages.Severity.ERROR, System.Label.Msg_Creditcard_CheckNumber);
            return false;
        } 

        if (!CreditcardUtility.isCVCPattenMatching(viewModel.account.CVC__c)) {
            addMessage(ApexPages.Severity.ERROR, System.Label.Msg_Creditcard_CheckCVC);
            return false;
        }

        return true;
    }
    
    private boolean updateReplenish() {
        for(Subscription__c sub : viewModel.subscriptions) {
            if(sub.id == subscriptionId) {
                sub.isReplenish__c = true;
                if(!viewModel.updateSubscription(sub))
                    return false; 
            }
        }
        return true;
    }

    private void rollbackAccount() {
        viewModel.account.credit_card_number__c = tempAccount.credit_card_number__c;
        viewModel.account.Expiration_month__c = tempAccount.Expiration_month__c;
        viewModel.account.CVC__c = tempAccount.CVC__c;
    }
}