force-app/main/default/objects/Account/fields/credit_card_number__c.field-meta.xml
<CustomField>
    <fullName>credit_card_number__c</fullName>
    <label>信用卡號</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CVC__c.field-meta.xml
<CustomField>
    <fullName>CVC__c</fullName>
    <label>CVC</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Expiration_month__c.field-meta.xml
<CustomField>
    <fullName>Expiration_month__c</fullName>
    <label>到期月份</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Expiration_Year_text__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Year_text__c</fullName>
    <label>到期年份</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>帳戶</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>帳戶</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/credit_card_number__c.field-meta.xml
<CustomField>
    <fullName>credit_card_number__c</fullName>
    <label>信用卡號</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/CVC__c.field-meta.xml
<CustomField>
    <fullName>CVC__c</fullName>
    <label>CVC</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Expiration_month__c.field-meta.xml
<CustomField>
    <fullName>Expiration_month__c</fullName>
    <label>到期月份</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <default>true</default>
                <label>01</label>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account__c/fields/Expiration_Year_text__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Year_text__c</fullName>
    <label>到期年份</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>訂閱</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}{000}</displayFormat>
        <label>訂單編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/viewModel/UpdateCreditCardViewModel.cls
public with sharing class UpdateCreditCardViewModel {

    private Account__c account;
    public List<Subscription__c> subscriptions {get; set;}
    private Account__c tempAccount {get; set;}
    public String errorMessage {get; set;}

    public UpdateCreditCardViewModel(String userId) {
        account = AccountModel.getAccountById(userId);
        subscriptions = SubscriptionModel.getSubscriptionsByUserId(userId);
        tempAccount = account.clone();
        
        account.CVC__c = '';
    }

    public Account__c getAccount() {
        return account;
    }

    public Boolean updateAccount() {
        if(checkField() == true){
            
            Database.UpsertResult result = Database.upsert(account);
            return result.isSuccess();    
        }

        return false;    
    }

    public Boolean checkField() {
        Boolean result = false;

        if (account.credit_card_number__c == null){
            errorMessage = '請填寫信用卡卡號';
        } else if (!isCreditCardPattenMatching(account.credit_card_number__c)) {
            errorMessage = '請確認您填寫的信用卡號是否正確';
        } else if (account.Expiration_month__c == null) {
            errorMessage = '請選擇到期月份';
        } else if (account.Expiration_Year_text__c == null) {
            errorMessage = '請選擇到期年份';
        } else if (account.CVC__c == null) {
            errorMessage = '請填寫CVC';
        } else if (account.CVC__c.length() != 3) {
            errorMessage = 'CVC須填三碼';
        } else {
            result = true;
        }

        return result;
    }

    private boolean isCreditCardPattenMatching(String str){
        boolean hasEng = false;
        Pattern MyPattern = Pattern.compile('^(?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\\d{3})\\d{11})$');
        Matcher MyMatcher = MyPattern.matcher(str);

        return MyMatcher.matches();
    }

    public void rollbackAccount() {
        account.credit_card_number__c = tempAccount.credit_card_number__c;
        account.Expiration_month__c = tempAccount.Expiration_month__c;
        
        account.CVC__c = tempAccount.CVC__c;
    }
}