force-app/main/default/objects/Account/fields/credit_card_number__c.field-meta.xml
<CustomField>
    <fullName>credit_card_number__c</fullName>
    <label>信用卡號</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>帳戶</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>帳戶</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/credit_card_number__c.field-meta.xml
<CustomField>
    <fullName>credit_card_number__c</fullName>
    <label>信用卡號</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMOPaymentBean__c/GMOPaymentBean__c.object-meta.xml
<CustomObject>
    <label>GMOPaymentBean</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>GMOPaymentBean Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>訂閱</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}{000}</displayFormat>
        <label>訂單編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Payment_method__c.field-meta.xml
<CustomField>
    <fullName>Payment_method__c</fullName>
    <label>付款方式</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>信用卡</fullName>
            </value>
            <value>
                <fullName>超商付款</fullName>
            </value>
            <value>
                <fullName>ATM轉帳</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SubscriptionRecipient__c/SubscriptionRecipient__c.object-meta.xml
<CustomObject>
    <label>訂閱Recipient</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>訂閱 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionRecipient__c/fields/ParentSubscription__c.field-meta.xml
<CustomField>
    <fullName>ParentSubscription__c</fullName>
    <label>訂閱</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>訂閱Recipient</relationshipLabel>
    <relationshipName>SubscriptionRecipient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SubscriptionRecipient__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <label>訂閱</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>訂閱Recipient</relationshipLabel>
    <relationshipName>SubscriptionRecipient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/viewModel/NewSubscriptionViewModel.cls
public with sharing class NewSubscriptionViewModel {
    public Account__c account {get; set;}
    public String errorMessage {get; set;}
    public CreditCardBean creditCardBean {get; set; }
    
    public NewSubscriptionViewModel(String accountId) {
        account = AccountModel.getAccountById(accountId);
        creditCardBean = new CreditCardBean();
    }

    public Boolean newSubscription(Subscription__c subscriptionToInsert, List<SubscriptionRecipient__c> recipients) {
        Boolean updateResult = true;  
        try {
            GMOPaymentBean__c gmoPaymentBean = ApexUtility.generateGMOPaymentBean(account, subscriptionToInsert, creditCardBean);
            GMOPaymentAPI gmoPaymentAPI = new GMOPaymentAPI(gmoPaymentBean);
            String transCode = gmoPaymentAPI.executePayment();
            
            if (transCode == null) {
                errorMessage = 'Payment went wrong.';
                return false;
            }

            GMOPaymentCheckOrderResultBean checkOrderResult = gmoPaymentAPI.checkOrder(System.Label.GMOPAYMENT_CONTRACT_CODE, transCode);

            Database.SaveResult dbInsertResult = Database.insert(subscriptionToInsert);
            updateResult = dbInsertResult.isSuccess();
            
            if (updateResult)
                for (SubscriptionRecipient__c recipient : recipients)
                    recipient.ParentSubscription__c = subscriptionToInsert.Id;

            List<Database.SaveResult> dbInsertRecipientsResults = Database.insert(recipients);
            for (Database.SaveResult dbInsertRecipientsResult : dbInsertRecipientsResults)
                if (!dbInsertRecipientsResult.isSuccess())
                    updateResult = false;

            if (updateResult)
                if (subscriptionToInsert.Payment_Method__c == '信用卡' && creditCardBean.cc != null && !String.isBlank(creditCardBean.cc))
                    account.credit_card_number__c = CreditcardUtility.hideCreditCardNumber(creditCardBean.cc);
            
            return updateResult;   
        } catch (DmlException ex) {
            errorMessage = ex.getMessage();
            return false;
        }
    }
}