force-app/main/default/objects/Account/fields/credit_card_number__c.field-meta.xml
<CustomField>
    <fullName>credit_card_number__c</fullName>
    <label>信用卡號</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>帳戶</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>帳戶</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/credit_card_number__c.field-meta.xml
<CustomField>
    <fullName>credit_card_number__c</fullName>
    <label>信用卡號</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>電子郵件</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>名字</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>訂閱</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}{000}</displayFormat>
        <label>訂單編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>訂單金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>收件人電子郵件</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>訂閱方案</label>
    <referenceTo>SubscriptionProgram__c</referenceTo>
    <relationshipLabel>訂閱</relationshipLabel>
    <relationshipName>Subscription_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionProgram__c/SubscriptionProgram__c.object-meta.xml
<CustomObject>
    <label>訂閱方案</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>訂閱方案名稱</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionProgram__c/fields/ProgramId__c.field-meta.xml
<CustomField>
    <fullName>ProgramId__c</fullName>
    <label>方案代號</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionProgram__c/fields/ProgramName__c.field-meta.xml
<CustomField>
    <fullName>ProgramName__c</fullName>
    <label>方案名稱</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/utility/ApexUtility.cls
public with sharing class ApexUtility {
    public static PageReference toPage(String myVar){
        PageReference page = new PageReference(URL.getSalesforceBaseUrl().toExternalForm() + '/apex/' + myVar);
    	page.setRedirect(true);
    	return page;  
    }

    public static String generateRandomAlphaNumeric(Integer size) {
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        String randomAlphaNumeric = '';

        for (Integer i = 0; i < size; i++) {
            Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
            randomAlphaNumeric += chars.substring(idx, idx+1);
        }
        return randomAlphaNumeric;
    }

    public static String generateRandomNumeric(Integer size) {
        final String chars = '0123456789';
        String randomAlphaNumeric = '';

        for (Integer i = 0; i < size; i++) {
            Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
            randomAlphaNumeric += chars.substring(idx, idx+1);
        }
        return randomAlphaNumeric;
    }

     public static String getUserIPAddress() {
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setHeader('content-type', 'application/json');
        req.setEndpoint( 'https://www.trackip.net/ip?json');
        Http http = new Http();
        HTTPResponse res = http.send(req);
        String jsonInput = res.getBody();
        
        Map<String,String> responseBodyMapped = (Map<String,String>)JSON.deserialize(jsonInput, Map<String,String>.class);
        		
        return responseBodyMapped.get('IP');
    }

    public static GMOPaymentBean generateGMOPaymentBean(Account__c account, Subscription__c subscription, CreditCardBean creditCardBean) {
        GMOPaymentBean gmoPaymentBean = generateGMOPaymentBean(account, subscription);
        
        if (account.credit_card_number__c == null) {
            gmoPaymentBean.card_number = creditCardBean.cc;
            gmoPaymentBean.expire_year = creditCardBean.expireYear;
            gmoPaymentBean.expire_month = creditCardBean.expireMonth;
            gmoPaymentBean.security_code = creditCardBean.cvc;
        }
        
        return gmoPaymentBean;
    }

    public static GMOPaymentBean generateGMOPaymentBean(Account__c account, Subscription__c subscription) {
        GMOPaymentBean gmoPaymentBean = new GMOPaymentBean();
        gmoPaymentBean.contract_code = '10081070';
        gmoPaymentBean.user_id = account.Id;
        gmoPaymentBean.user_name = account.LastName__c;
        gmoPaymentBean.user_mail_add = account.Email__c;

        gmoPaymentBean.card_holder_name = account.LastName__c;
        System.debug(subscription.Id);
        gmoPaymentBean.ip_address = ApexUtility.getUserIPAddress();
        SubscriptionProgram__c program = [SELECT ProgramId__c, ProgramName__c FROM SubscriptionProgram__c WHERE ID = :subscription.Program__c];
        gmoPaymentBean.item_code = program.ProgramId__c;
        gmoPaymentBean.item_name = program.ProgramName__c;
        gmoPaymentBean.order_number = ApexUtility.generateRandomNumeric(4) + Datetime.now().format('yyyyMMddHHmmss');
        gmoPaymentBean.item_price = String.valueOf(subscription.Amount__c);

        return gmoPaymentBean;
    }
    
}