force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>帳戶</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>帳戶</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>電子郵件</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/test/RegisterControllerTestCase.cls
@isTest
public with sharing class RegisterControllerTestCase {
    static testMethod void testRegister_Wrong_Email_Format_Return_Null() {
        RegisterController controller = new RegisterController();
        controller.viewModel.account.Email__c = 'jin@ccc';
        Pagereference page = controller.register();
        System.assertEquals(null, page);
        System.assertEquals(System.Label.Msg_EmailFormat, controller.baseErrorMessage);
    }

    static testMethod void testRegister_Account_Exist_Return_Null() {
        String email = 'jin@ccc.com';
        Account__c account = new Account__c();
        account.Email__c = email;
        insert account;
        RegisterController controller = new RegisterController();
        controller.viewModel.account.Email__c = email;
        Pagereference page = controller.register();
        System.assertEquals(null, page);
        System.assertEquals(System.Label.Msg_AccountAlreadyExist, controller.baseErrorMessage);
    }

    static testMethod void testRegister_Normal_Register_Return_Not_Null() {
        RegisterController controller = new RegisterController();
        controller.viewModel.account.Email__c = 'jin@xxx.com';
        Pagereference page = controller.register();
        System.assertNotEquals(null, page);
    }
}