force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>地址</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>地址名稱</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>地區</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>縣市</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>訂閱</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}{000}</displayFormat>
        <label>訂單編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/AccountStandard__c.field-meta.xml
<CustomField>
    <fullName>AccountStandard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountStandard</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>訂閱</relationshipLabel>
    <relationshipName>SubAcc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>地址</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Area_picklist__c.field-meta.xml
<CustomField>
    <fullName>Area_picklist__c</fullName>
    <label>地區(選項)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>City_picklist__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>中正區</fullName>
            </value>
            <value>
                <fullName>大同區</fullName>
            </value>
            <value>
                <fullName>中山區</fullName>
            </value>
            <value>
                <fullName>松山區</fullName>
            </value>
            <value>
                <fullName>大安區</fullName>
            </value>
            <value>
                <fullName>萬華區</fullName>
            </value>
            <value>
                <fullName>信義區</fullName>
            </value>
            <value>
                <fullName>士林區</fullName>
            </value>
            <value>
                <fullName>北投區</fullName>
            </value>
            <value>
                <fullName>內湖區</fullName>
            </value>
            <value>
                <fullName>南港區</fullName>
            </value>
            <value>
                <fullName>文山區</fullName>
            </value>
            <value>
                <fullName>仁愛區</fullName>
            </value>
            <value>
                <fullName>安樂區</fullName>
            </value>
            <value>
                <fullName>暖暖區</fullName>
            </value>
            <value>
                <fullName>七堵區</fullName>
            </value>
            <value>
                <fullName>南竿鄉</fullName>
            </value>
            <value>
                <fullName>北竿鄉</fullName>
            </value>
            <value>
                <fullName>莒光鄉</fullName>
            </value>
            <value>
                <fullName>東引鄉</fullName>
            </value>
            <value>
                <fullName>萬里區</fullName>
            </value>
            <value>
                <fullName>金山區</fullName>
            </value>
            <value>
                <fullName>板橋區</fullName>
            </value>
            <value>
                <fullName>汐止區</fullName>
            </value>
            <value>
                <fullName>深坑區</fullName>
            </value>
            <value>
                <fullName>石碇區</fullName>
            </value>
            <value>
                <fullName>瑞芳區</fullName>
            </value>
            <value>
                <fullName>平溪區</fullName>
            </value>
            <value>
                <fullName>雙溪區</fullName>
            </value>
            <value>
                <fullName>貢寮區</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/City_picklist__c.field-meta.xml
<CustomField>
    <fullName>City_picklist__c</fullName>
    <label>縣市(選項)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>台北市</fullName>
            </value>
            <value>
                <fullName>基隆市</fullName>
            </value>
            <value>
                <fullName>新北市</fullName>
            </value>
            <value>
                <fullName>連江縣</fullName>
            </value>
            <value>
                <fullName>宜蘭縣</fullName>
            </value>
            <value>
                <fullName>新竹市</fullName>
            </value>
            <value>
                <fullName>新竹縣</fullName>
            </value>
            <value>
                <fullName>桃園市</fullName>
            </value>
            <value>
                <fullName>苗栗縣</fullName>
            </value>
            <value>
                <fullName>台中市</fullName>
            </value>
            <value>
                <fullName>彰化縣</fullName>
            </value>
            <value>
                <fullName>南投縣</fullName>
            </value>
            <value>
                <fullName>嘉義市</fullName>
            </value>
            <value>
                <fullName>嘉義縣</fullName>
            </value>
            <value>
                <fullName>雲林縣</fullName>
            </value>
            <value>
                <fullName>台南市</fullName>
            </value>
            <value>
                <fullName>高雄市</fullName>
            </value>
            <value>
                <fullName>澎湖縣</fullName>
            </value>
            <value>
                <fullName>金門縣</fullName>
            </value>
            <value>
                <fullName>屏東縣</fullName>
            </value>
            <value>
                <fullName>台東縣</fullName>
            </value>
            <value>
                <fullName>花蓮縣</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>收件人電子郵件</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/isReplenish__c.field-meta.xml
<CustomField>
    <fullName>isReplenish__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動續訂</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <label>收件人名稱</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Tel__c.field-meta.xml
<CustomField>
    <fullName>Tel__c</fullName>
    <label>電話</label>
    <type>Phone</type>
</CustomField>

force-app/test/SubscriptionManagerControllerTestCase.cls
@isTest
public with sharing class SubscriptionManagerControllerTestCase {
    @testSetup
    public static void createAccountForTest() {
        Account account = new Account(PersonEmail = 'jin@ifpa.com', LastName = 'Jin');
        account.recordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'PersonAccount' and SObjectType = 'Account'].Id;
        
        insert account;
    }

    public static testMethod void testSunmitForm() {
        Account account = [SELECT ID FROM Account WHERE PersonEmail = 'jin@ifpa.com'];
        SubscriptionManagementController controller = new SubscriptionManagementController(account.id);
        Pagereference page = controller.submitForm();
        System.assertEquals('', controller.currentEditRowId);
        System.assertEquals(null, page);
    }
    
    public static testMethod void testStopAutoOrderPanel() {
        Account account = [SELECT ID FROM Account WHERE PersonEmail = 'jin@ifpa.com'];
        SubscriptionManagementController controller = new SubscriptionManagementController(account.id);
        Pagereference page = controller.stopAutoOrderPanel();
        System.assertEquals(null, page);
    }

    public static testMethod void testStopAutoOrderService() {
        Account account = [SELECT ID FROM Account WHERE PersonEmail = 'jin@ifpa.com'];
        SubscriptionManagementController controller = new SubscriptionManagementController(account.id);
        Pagereference page = controller.stopAutoOrderService();
        System.assertEquals(false, controller.updatedCreditcard);
        System.assertEquals('', controller.currentCancelRowId);
        System.assertEquals(null, page);
    }

    public static testMethod void testUseAutoOrderPanel() {
        Account account = [SELECT ID FROM Account WHERE PersonEmail = 'jin@ifpa.com'];
        SubscriptionManagementController controller = new SubscriptionManagementController(account.id);
        Pagereference page = controller.useAutoOrderPanel();
        System.assertEquals(null, page);
    }

    public static testMethod void testUseAutoOrderService() {
        Account account = [SELECT ID FROM Account WHERE PersonEmail = 'jin@ifpa.com'];
        SubscriptionManagementController controller = new SubscriptionManagementController(account.id);
        controller.currentUseRowId = '123';
        Pagereference page = controller.useAutoOrderService();
        System.assertEquals('123', controller.subIdForUpdateCredit);
        System.assertEquals('', controller.currentUseRowId);
        System.assertEquals(null, page);
    }

    public static testMethod void testUseAutoOrderService_isReplenish_True() {
        Account account = [SELECT ID FROM Account WHERE PersonEmail = 'jin@ifpa.com'];
        Subscription__c tempSub = new Subscription__c(AccountStandard__c = account.id);
        insert tempSub;
        SubscriptionManagementController controller = new SubscriptionManagementController(account.id);
        controller.currentUseRowId = tempSub.id;
        Pagereference page = controller.useAutoOrderService();
        for (Subscription__c sub : controller.viewModel.subscriptions) {
            System.assertEquals(true, sub.isReplenish__c);
        }
        
    }

    public static testMethod void testChangeRecipientInfo() {
        Account account = [SELECT ID FROM Account WHERE PersonEmail = 'jin@ifpa.com'];
        SubscriptionManagementController controller = new SubscriptionManagementController(account.id);
        Pagereference page = controller.changeRecipientInfo();
        System.assertEquals(null, page);
    }

    public static testMethod void testCancelReturn() {
        Account account = [SELECT ID FROM Account WHERE PersonEmail = 'jin@ifpa.com'];
        SubscriptionManagementController controller = new SubscriptionManagementController(account.id);
        Pagereference page = controller.cancelReturn();
        System.assertEquals('', controller.currentUseRowId);
        System.assertEquals('', controller.currentCancelRowId);
        System.assertEquals(null, page);
    }

    public static testMethod void testcancelChange() {
        Account account = [SELECT ID FROM Account WHERE PersonEmail = 'jin@ifpa.com'];
        SubscriptionManagementController controller = new SubscriptionManagementController(account.id);
        Pagereference page = controller.cancelChange();
        System.assertEquals('', controller.currentEditRowId);
        System.assertEquals(null, page);
    }

    public static testMethod void testAfterSubmit() {
        Account account = [SELECT ID FROM Account WHERE PersonEmail = 'jin@ifpa.com'];
        SubscriptionManagementController controller = new SubscriptionManagementController(account.id);
        Pagereference page = controller.afterSubmit();
        System.assertEquals(0, controller.viewModel.subscriptions.size());
        System.assertEquals(null, page);
    }

    public static testMethod void testCheckField_Recipient_Not_Complete_Return_Msg() {
        Account account = [SELECT ID FROM Account WHERE PersonEmail = 'jin@ifpa.com'];
        Subscription__c tempSub = new Subscription__c(AccountStandard__c = account.id);
        insert tempSub;
        SubscriptionManagementController controller = new SubscriptionManagementController(account.id);
        Pagereference page = controller.submitForm();
        System.assertEquals(System.Label.Msg_RecipientInfoEmpty, controller.baseErrorMessage); 
    }

    public static testMethod void testCheckField_Address_Email_Null_Return_Msg() {
        Address__c address = new Address__c(City__c = '台北', Area__c = '松山區');
        insert address;
        Account account = [SELECT ID FROM Account WHERE PersonEmail = 'jin@ifpa.com'];
        Subscription__c tempSub = new Subscription__c(AccountStandard__c = account.id, Recipient__c = '123');
        insert tempSub;
        SubscriptionManagementController controller = new SubscriptionManagementController(account.id);
        controller.viewModel.subscriptions.get(0).City_picklist__c = '台北';
        controller.viewModel.subscriptions.get(0).Area_picklist__c = '松山區';
        Pagereference page = controller.submitForm();
        System.assertEquals(System.Label.Msg_RecipientInfoEmpty, controller.baseErrorMessage); 
    }

    public static testMethod void testCheckField_Tel_Null_Return_Msg() {
        Address__c address = new Address__c(City__c = '台北', Area__c = '松山區');
        insert address;
        Account account = [SELECT ID FROM Account WHERE PersonEmail = 'jin@ifpa.com'];
        Subscription__c tempSub = new Subscription__c(AccountStandard__c = account.id, Recipient__c = '123');
        insert tempSub;
        SubscriptionManagementController controller = new SubscriptionManagementController(account.id);
        controller.viewModel.subscriptions.get(0).City_picklist__c = '台北';
        controller.viewModel.subscriptions.get(0).Area_picklist__c = '松山區';
        controller.viewModel.subscriptions.get(0).Address__c = '123';
        controller.viewModel.subscriptions.get(0).Email__c = 'jin@4idps.com';
        controller.viewModel.subscriptions.get(0).Tel__c = '123';
        Pagereference page = controller.submitForm();
        System.assertNotEquals(System.Label.Msg_RecipientInfoEmpty, controller.baseErrorMessage); 
        System.assertEquals(System.Label.Msg_PhoneFormat, controller.baseErrorMessage);
    }

    public static testMethod void testSubmitForm_CheckField_True() {
        Address__c address = new Address__c(City__c = '台北市', Area__c = '松山區');
        insert address;
        Account account = [SELECT ID FROM Account WHERE PersonEmail = 'jin@ifpa.com'];
        Subscription__c tempSub = new Subscription__c(AccountStandard__c = account.id, Recipient__c = '123');
        insert tempSub;
        SubscriptionManagementController controller = new SubscriptionManagementController(account.id);
        controller.viewModel.subscriptions.get(0).City_picklist__c = '台北市';
        controller.viewModel.subscriptions.get(0).Area_picklist__c = '松山區';
        controller.viewModel.subscriptions.get(0).Address__c = '123';
        controller.viewModel.subscriptions.get(0).Email__c = 'jin@4idps.com';
        controller.viewModel.subscriptions.get(0).Tel__c = '0987888222';
        Pagereference page = controller.submitForm();
        System.assertEquals(System.Label.Msg_SaveSuccess, controller.baseErrorMessage);
        System.assertEquals('', controller.currentEditRowId);
    }

    public static testMethod void testTurn_To_UpdateCreditcardPage() {
        SubscriptionManagementController controller = new SubscriptionManagementController();
        Pagereference page = controller.toUpdateCreditcardPage();
        System.assertNotEquals(null, page);
    }

    public static testMethod void testTurn_To_SummaryPage() {
        SubscriptionManagementController controller = new SubscriptionManagementController();
        Pagereference page = controller.toSummaryPage();
        System.assertNotEquals(null, page);
    }

    public static testMethod void testTurn_To_AccountSettingPage() {
        SubscriptionManagementController controller = new SubscriptionManagementController();
        Pagereference page = controller.toAccountSettingPage();
        System.assertNotEquals(null, page);
    }
    public static testMethod void testTurn_To_SubscriptionManagementPage() {
        SubscriptionManagementController controller = new SubscriptionManagementController();
        Pagereference page = controller.toSubscriptionManagementPage();
        System.assertNotEquals(null, page);
    }

    public static testMethod void testLogOut() {
        SubscriptionManagementController controller = new SubscriptionManagementController();
        Pagereference page = controller.logOut();
        System.assertNotEquals(null, page);
    }
}