force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>帳戶</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>帳戶</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>電子郵件</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/test/updateCreditCardTestCases.cls
@isTest
public  class updateCreditCardTestCases {
    public static testMethod void testViewModel_Constuctor() {
        Account__c account = new Account__c(Email__c = 'jin@ga.com');
        insert account;
        UpdateCreditCardViewModel viewModel = new UpdateCreditCardViewModel(account.id);
        System.assertNotEquals(null, viewModel.account);
        System.assertNotEquals(null, viewModel.subscriptions);
        System.assertNotEquals(null, viewModel.creditCardBean); 
    }

    public static testMethod void testUpdateAccount() {
        Account__c account = new Account__c(Email__c = 'jin@ga.com');
        insert account;
        UpdateCreditCardViewModel viewModel = new UpdateCreditCardViewModel(account.id);
        Boolean result = viewModel.updateAccount();
        System.assertEquals(true, result);
    }
}