force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>帳戶</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>帳戶</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>電子郵件</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>訂閱</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}{000}</displayFormat>
        <label>訂單編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/CustomAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomAccount__c</fullName>
    <label>帳戶</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>訂閱</relationshipLabel>
    <relationshipName>AccSub</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>收件人電子郵件</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SubscriptionProgram__c/SubscriptionProgram__c.object-meta.xml
<CustomObject>
    <label>訂閱方案</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>訂閱方案名稱</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/TestSubscriptionModel.cls
@isTest
public with sharing class TestSubscriptionModel {
    public static testMethod void testGetSubscriptionsByUserId() {
        Account__c account = new Account__c(Email__c = 'jin@4idps.com');
       
        Subscription__c sub = new Subscription__c(CustomAccount__c = account.Id);
       
        List<Subscription__c> subs = SubscriptionModel.getSubscriptionsByUserId(account.Id);
        System.assertNotEquals(null, subs);
    }

    public static testMethod void testGetProgram() {
        SubscriptionProgram__c program = new SubscriptionProgram__c();
        insert program;
        List<SubscriptionProgram__c> programs = SubscriptionModel.getProgram();
        System.assertNotEquals(null, programs);
    }

    public static testMethod void testGetProgramById() {
        SubscriptionProgram__c program = new SubscriptionProgram__c();
        insert program;
        List<SubscriptionProgram__c> programs = SubscriptionModel.getProgramById(program.Id);
        System.assertNotEquals(null, programs);
    }

    public static testMethod void testGetUniqueSubscriptionById_Success() {
        Account__c account = new Account__c(Email__c = 'jin@rrr.com');
        insert account;
        Subscription__c subscription = new Subscription__c(CustomAccount__c = account.id);
        insert subscription;
        Subscription__c sub = SubscriptionModel.getUniqueSubscriptionById(subscription.id);
        System.assertNotEquals(null, sub);
    }

    public static testMethod void testGetUniqueSubscriptionById_Not_Find_Return_Null() {
        Subscription__c sub = SubscriptionModel.getUniqueSubscriptionById('123');
        System.assertEquals(null, sub);
    }
}