force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>12</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>帳戶</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>帳戶</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>電子郵件</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>名字</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>密码</label>
    <length>12</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/test/loginTestCases.cls
@isTest
public class loginTestCases {
    public static testMethod void testLoginSucceed() {
        
        //Prepare env
        String password = '1234';
        String email = 'alan.feng@4idps.com';
        Account__c preAccount = new Account__c(LastName__c = 'Alan', Password__c = password, Email__c = email);
        insert preAccount;

        //Test constructor
        LoginController controller = new LoginController();
        System.assertNotEquals(null, controller.viewModel.account);

        //Test function
        Account__c account = controller.viewModel.account;
        account.Password__c = password;
        account.Email__c = email;
        
        //controller.submit();

    }

    public static testMethod void testLoginFailed() {

    }
}