force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>帳戶</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>帳戶</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>電子郵件</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/controller/RegisterController.cls
public with sharing class RegisterController extends ApexBaseController {
    public RegisterViewModel viewModel {get; set;}

    public RegisterController() {
        viewModel = new RegisterViewModel();       
    }

    public Pagereference register() {      
        if (registerByEmail()) { 
            PageReference page = new PageReference(URL.getSalesforceBaseUrl().toExternalForm() + '/apex/RegisterResultPage');
            page.getParameters().put('id', viewModel.account.Id);
            page.setRedirect(true);
            
            return page;
        }
        return null;
    }

    public Boolean registerByEmail() {
        if (!EmailUtility.emailFormatValidation(viewModel.account.Email__c)) { 
            addMessage(ApexPages.Severity.ERROR, System.Label.Msg_EmailFormat);  
            return false;
        }

        if (AccountModel.getAccountByEmail(viewModel.account.Email__c) != null) {
            addMessage(ApexPages.Severity.ERROR, System.Label.Msg_AccountAlreadyExist); 
            return false;
        }

        Account__c accountCreated = AccountModel.createAccountByEmail(viewModel.account.Email__c);
        
        // Jin: no need to check here
        // if (accountCreated == null) {
        //     addMessage(ApexPages.Severity.ERROR, System.Label.Msg_AccountAlreadyExist); 
        //     return false;
        // }
        
        viewModel.account = accountCreated;

        if (EmailUtility.sendEmail(viewModel.account.Email__c, 'AccountActivation'))
            return true;
        
        addMessage(ApexPages.Severity.ERROR, System.Label.Msg_EmailSendFail); 
        return false;
    }
}