force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>帳戶</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>帳戶</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>電子郵件</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/test/RegisterResultTestCase.cls
@isTest
public with sharing class RegisterResultControllerTestCase {
    public static testMethod void testGetAccount_Info() {
        Account__c account = new Account__c(Email__c = 'jin@4idps.com');
        insert account;
        Test.setCurrentPage(Page.RegisterResultPage);
        ApexPages.currentPage().getParameters().put('id',account.id);
        RegisterResultController controller = new RegisterResultController();
        System.assertNotEquals(null, controller.viewModel);
    }

    public static testMethod void testViewModel_Get_Account() {
        Account__c account = new Account__c(Email__c = 'jin@4idps.com');
        insert account;
        Test.setCurrentPage(Page.RegisterResultPage);
        ApexPages.currentPage().getParameters().put('id',account.id);
        
        RegisterResultController controller = new RegisterResultController();
        Account__c accountForViewModel = controller.viewModel.getAccount();
        System.assertNotEquals(null, accountForViewModel);
    }
}