force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>帳戶</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>帳戶</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>電子郵件</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/viewModel/RegisterViewModel.cls
public with sharing class RegisterViewModel {

    public Account__c account {get; set;}
    private String errorMessage {get; set;} 

    public enum RegisterType {
        Email,
        Facebook,
        Google
    }

    public RegisterViewModel() {
        account = new Account__c();
    }

    public Boolean registerByEmail() {
        if (!EmailUtility.emailFormatValidation(account.Email__c)) {
            errorMessage = '電子郵件格式不符';   
            return false;
        }
        if (AccountModel.getAccountByEmail(account.Email__c) != null) {
            errorMessage = '帳號已存在';   
            return false;
        }

        Account__c accountCreated = AccountModel.createAccountByEmail(account.Email__c);
        if (accountCreated == null) {
            errorMessage = '帳號已存在';
            return false;
        }

        if (EmailUtility.sendEmail(account.Email__c, 'AccountActivation'))
            return true;
        
        errorMessage = '電子郵件寄送失敗';   
        return false;
    }

    public String getErrorMessage() {
        return errorMessage;
    }
}