force-app/main/default/objects/Account/fields/JoinDate__c.field-meta.xml
<CustomField>
    <fullName>JoinDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>加入日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>帳戶</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>帳戶</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/JoinDate__c.field-meta.xml
<CustomField>
    <fullName>JoinDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>加入日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>訂閱</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}{000}</displayFormat>
        <label>訂單編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/viewModel/SummaryViewModel.cls
public with sharing class SummaryViewModel {
    private Account__c account;
    private List<Subscription__c> subscriptions;
    
    public String year {get; set;}
    public String month {get; set;}
    public String day {get; set;}
    private Integer sumOfSubscription {get; set;}
    
    public SummaryViewModel(String userId) {
        account = AccountModel.getAccountById(userId);
        subscriptions = SubscriptionModel.getSubscriptionsByUserId(userId);
        
        Datetime joinDate = (Datetime)account.JoinDate__c;
        year = joinDate.format('Y');
        month = joinDate.format('M');
        day = joinDate.format('d');

    }
    
    public Account__c getAccount() {
        return account;
    }

    public List<Subscription__c> getSubscriptions() {
        return subscriptions;
    }
    
    public Integer getSumOfSubscription(){
        sumOfSubscription = 0;
        for(Subscription__c sub : subscriptions){
            sumOfSubscription ++;
        }
        
        return sumOfSubscription;
    }
}