force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>訂閱</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}{000}</displayFormat>
        <label>訂單編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Payment_status__c.field-meta.xml
<CustomField>
    <fullName>Payment_status__c</fullName>
    <label>付款狀態</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>paymentpending</fullName>
                <default>true</default>
                <label>待付款</label>
            </value>
            <value>
                <fullName>paymentdone</fullName>
                <label>已付款</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/cronjob/CheckPaymentBatchJob.cls
public with sharing class CheckPaymentBatchJob implements Database.Batchable<SObject>, Database.AllowsCallouts {
    public Subscription__c subscription {get; set;}
    public String transCode {get; set;}
    
    public CheckPaymentBatchJob(Subscription__c subscriptionParam, String transCodeParam) {
        subscription = subscriptionParam;
        transCode = transCodeParam;
        
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        GMOPaymentAPI gmoPaymentAPI = new GMOPaymentAPI(null);
        GMOPaymentCheckOrderResultBean checkOrderResult = gmoPaymentAPI.checkOrder(System.Label.GMOPAYMENT_CONTRACT_CODE, transCode);

        if (checkOrderResult.GlobalPayment_result.state == '5') {
            subscription.Payment_status__c = Constants.PAYMENT_STATUS_DONE;
            update subscription;
        }

        String query = 'SELECT Id From account';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext info, List<SObject> opportunities) {}

    public void finish(Database.BatchableContext info) { }

}