force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>訂閱</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}{000}</displayFormat>
        <label>訂單編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>訂單金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Company_name__c.field-meta.xml
<CustomField>
    <fullName>Company_name__c</fullName>
    <label>公司抬頭</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/CustomAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomAccount__c</fullName>
    <label>帳戶</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>訂閱</relationshipLabel>
    <relationshipName>AccSub</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/End_period__c.field-meta.xml
<CustomField>
    <fullName>End_period__c</fullName>
    <label>訂閱結束期數</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/isInvoice__c.field-meta.xml
<CustomField>
    <fullName>isInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>開立發票</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/isReplenish__c.field-meta.xml
<CustomField>
    <fullName>isReplenish__c</fullName>
    <defaultValue>true</defaultValue>
    <label>自動續訂</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/memberInfo__c.field-meta.xml
<CustomField>
    <fullName>memberInfo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>同會員帳戶資料</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Not_received__c.field-meta.xml
<CustomField>
    <fullName>Not_received__c</fullName>
    <label>沒收到次數</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>備註</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Order_date__c.field-meta.xml
<CustomField>
    <fullName>Order_date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>訂單日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Payment_date__c.field-meta.xml
<CustomField>
    <fullName>Payment_date__c</fullName>
    <label>付款日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Payment_method__c.field-meta.xml
<CustomField>
    <fullName>Payment_method__c</fullName>
    <label>付款方式</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>信用卡</fullName>
            </value>
            <value>
                <fullName>超商付款</fullName>
            </value>
            <value>
                <fullName>ATM轉帳</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Payment_status__c.field-meta.xml
<CustomField>
    <fullName>Payment_status__c</fullName>
    <label>付款狀態</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>paymentpending</fullName>
                <default>true</default>
                <label>待付款</label>
            </value>
            <value>
                <fullName>paymentdone</fullName>
                <label>已付款</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>訂閱方案</label>
    <referenceTo>SubscriptionProgram__c</referenceTo>
    <relationshipLabel>訂閱</relationshipLabel>
    <relationshipName>Subscription_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Start_period__c.field-meta.xml
<CustomField>
    <fullName>Start_period__c</fullName>
    <label>訂閱開始期數</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_item__c.field-meta.xml
<CustomField>
    <fullName>Subscription_item__c</fullName>
    <label>訂閱方案</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>訂閱10期 800元</fullName>
                <default>true</default>
                <label>訂閱10期 800元</label>
            </value>
            <value>
                <fullName>訂閱5期 400元</fullName>
            </value>
            <value>
                <fullName>訂閱20期 1600元</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_status__c.field-meta.xml
<CustomField>
    <fullName>Subscription_status__c</fullName>
    <label>訂閱狀態</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>訂單成立</fullName>
                <default>true</default>
                <label>訂單成立</label>
            </value>
            <value>
                <fullName>訂閱中</fullName>
            </value>
            <value>
                <fullName>結案</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Tax_No__c.field-meta.xml
<CustomField>
    <fullName>Tax_No__c</fullName>
    <label>統一編號</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionProgram__c/SubscriptionProgram__c.object-meta.xml
<CustomObject>
    <label>訂閱方案</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>訂閱方案名稱</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionProgram__c/fields/Order_Period__c.field-meta.xml
<CustomField>
    <fullName>Order_Period__c</fullName>
    <label>期數</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SubscriptionProgram__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>價格</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SubscriptionProgram__c/fields/ProgramId__c.field-meta.xml
<CustomField>
    <fullName>ProgramId__c</fullName>
    <label>方案代號</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionProgram__c/fields/ProgramName__c.field-meta.xml
<CustomField>
    <fullName>ProgramName__c</fullName>
    <label>方案名稱</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/model/SubscriptionModel.cls
public with sharing class SubscriptionModel {
    public SubscriptionModel() {

    }

    public static List<Subscription__c> getSubscriptionsByUserId(String userId) {
        return [Select Id, Program__r.Order_Period__c, Program__r.ProgramName__c, Program__c, Name, Amount__c, Start_period__c, End_Period__c, 
        Payment_method__c, Payment_status__c, Company_name__c, isInvoice__c, isReplenish__c, memberInfo__c, Not_received__c, Note__c, Order_date__c,
        Payment_date__c, Subscription_item__c, Subscription_status__c, Tax_No__c
        FROM Subscription__c where CustomAccount__c = :userId];
    }
    

    public static List<SubscriptionProgram__c> getProgram() {
        return [SELECT Id, Price__c, ProgramId__c, ProgramName__c, Order_Period__c FROM SubscriptionProgram__c Order by Price__c];
    }

    public static List<SubscriptionProgram__c> getProgramById(String programId) {
        return [SELECT Id, Price__c, ProgramId__c, ProgramName__c, Order_Period__c FROM SubscriptionProgram__c WHERE ProgramId__c =: programId  Order by Price__c LIMIT 1] ;
    }
}