force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>訂閱</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}{000}</displayFormat>
        <label>訂單編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/AccountStandard__c.field-meta.xml
<CustomField>
    <fullName>AccountStandard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountStandard</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>訂閱</relationshipLabel>
    <relationshipName>SubAcc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/test/SubscriptionManagerViewModelTestCase.cls
@isTest
public with sharing class SubscriptionManagerViewModelTestCase {
    public static testMethod void testViewModelSubmitSubscription() {
        Account account = new Account(PersonEmail = 'jin@ifpa.com', LastName = 'Jin');
        account.recordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'PersonAccount' and SObjectType = 'Account'].Id;
        insert account;
        SubscriptionManagementController controller = new SubscriptionManagementController(account.id);
        Subscription__c subscription = new Subscription__c(AccountStandard__c = account.id);
        Boolean submitResult = controller.viewModel.submit(subscription);
        System.assertEquals(true, submitResult);
    }
}