force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>地址</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>地址名稱</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>地區</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>縣市</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>郵遞區號</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/test/TestAddressModel.cls
@isTest
public with sharing class TestAddressModel {
    public static testMethod void testGetZipCodeByArea_ReturnNull() {
        String zipcode = AddressModel.getZipCodeByArea('台北市','松山區' );
        System.assertEquals(null, zipcode);
    }

    public static testMethod void testGetZipCodeByArea() {
         Address__c address = new Address__c(City__c = '台北市', Area__c = '松山區', Zipcode__c = '105');
         insert address;
        String zipcode = AddressModel.getZipCodeByArea('台北市','松山區' );
        System.assertNotEquals(null, zipcode );
    }
}