force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>地址</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>地址名稱</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>地區</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>縣市</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>郵遞區號</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/model/AddressModel.cls
public with sharing class AddressModel {
    public AddressModel() {

    }
      
    public static String getZipCodeByArea(String city, String area) {
        Address__c zipCode = new Address__c();
        zipCode = [SELECT id, City__c, Area__c, Zipcode__c FROM Address__c WHERE City__c =:city AND Area__c =: area LIMIT 1];

        if (zipCode == null) 
            return null;
        
        return zipCode.Zipcode__c;
    }

    
}