force-app/main/default/objects/ApexLog__c/ApexLog__c.object-meta.xml
<CustomObject>
    <label>ApexLog</label>
    <nameField>
        <label>ApexLog Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApexLog__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>ClassName</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApexLog__c/fields/DateLog__c.field-meta.xml
<CustomField>
    <fullName>DateLog__c</fullName>
    <defaultValue>$System.OriginDateTime</defaultValue>
    <label>DateLog</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ApexLog__c/fields/LevelLog__c.field-meta.xml
<CustomField>
    <fullName>LevelLog__c</fullName>
    <label>LevelLog</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApexLog__c/fields/LineLog__c.field-meta.xml
<CustomField>
    <fullName>LineLog__c</fullName>
    <label>LineLog</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApexLog__c/fields/MessageLog__c.field-meta.xml
<CustomField>
    <fullName>MessageLog__c</fullName>
    <label>MessageLog</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApexLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <label>MethodName</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApexLogger.cls
global class ApexLogger {

    public Enum TYPE_LOG {
        DEBUG,
        ERROR,
        INFO
    }

    global static String getClassName(String trace) {
        if (trace.startsWith('Class.'))
            trace = trace.substringAfter('Class.');
        return trace.substringBefore(':').substringBeforeLast('.');
    }

    global static String getMethod(String trace) {
        return trace.substringBefore(':').substringAfterLast('.');
    }

    public virtual class Log {
        public String levelLog {get; set;}
        public Date dateLog {get; set;}
        public String className {get; set;}
        public String methodName {get; set;}
        public Integer lineLog {get; set;}
        public String messageLog {get; set;}

        public void saveLog(Log logItem) {
            System.debug('logItem=' + logItem);
            ApexLog__c apexLog = new ApexLog__c();
            apexLog.LevelLog__c = logItem.levelLog;
            apexLog.DateLog__c = logItem.dateLog;
            apexLog.ClassName__c = logItem.className;
            apexLog.MethodName__c = logItem.methodName;
            apexLog.LineLog__c = logItem.lineLog;
            apexLog.MessageLog__c = logItem.messageLog;

            insert apexLog;
        }
    }

    public class ErrorLog extends Log {
        public ErrorLog (Exception ex) {
            this.levelLog = String.valueOf(ApexLogger.TYPE_LOG.ERROR);
            this.dateLog = Date.today();
            String trace = new DmlException().getStackTraceString().substringAfter('\n');
            this.className = ApexLogger.getClassName(trace);
            this.methodName = ApexLogger.getMethod(trace);
            this.lineLog = ex.getLineNumber();
            this.messageLog = ex.getMessage();
            saveLog(this);
        }
    }

    public class InfoLog extends Log {
        public InfoLog (String classNameParam, String methodNameParam, String messageLogParam) {
            this.levelLog = String.valueOf(ApexLogger.TYPE_LOG.INFO);
            this.dateLog = Date.today();
            this.className = classNameParam;
            this.methodName = methodNameParam;
            this.messageLog = messageLogParam;
            saveLog(this);
        }
    }
}